"""
Shared test case definitions for the Simple CLI Calculator.
Each test case is executed directly against the functions in calculator.py
(add, subtract, multiply, divide, power, square_root).
"""

TEST_CASES = [
    {
        "id": "TC01",
        "scenario": "Addition of two positive numbers",
        "function": "add",
        "inputs": (5, 3),
        "steps": "Call add(5, 3)",
        "expected": "8",
        "check": "value",
        "expected_value": 8,
    },
    {
        "id": "TC02",
        "scenario": "Addition with a negative number",
        "function": "add",
        "inputs": (-5, 3),
        "steps": "Call add(-5, 3)",
        "expected": "-2",
        "check": "value",
        "expected_value": -2,
    },
    {
        "id": "TC03",
        "scenario": "Subtraction of two positive numbers",
        "function": "subtract",
        "inputs": (10, 4),
        "steps": "Call subtract(10, 4)",
        "expected": "6",
        "check": "value",
        "expected_value": 6,
    },
    {
        "id": "TC04",
        "scenario": "Subtraction resulting in a negative number",
        "function": "subtract",
        "inputs": (3, 10),
        "steps": "Call subtract(3, 10)",
        "expected": "-7",
        "check": "value",
        "expected_value": -7,
    },
    {
        "id": "TC05",
        "scenario": "Multiplication of two positive numbers",
        "function": "multiply",
        "inputs": (6, 7),
        "steps": "Call multiply(6, 7)",
        "expected": "42",
        "check": "value",
        "expected_value": 42,
    },
    {
        "id": "TC06",
        "scenario": "Multiplication by zero",
        "function": "multiply",
        "inputs": (5, 0),
        "steps": "Call multiply(5, 0)",
        "expected": "0",
        "check": "value",
        "expected_value": 0,
    },
    {
        "id": "TC07",
        "scenario": "Normal division",
        "function": "divide",
        "inputs": (10, 2),
        "steps": "Call divide(10, 2)",
        "expected": "5.0",
        "check": "value",
        "expected_value": 5.0,
    },
    {
        "id": "TC08",
        "scenario": "Division by zero",
        "function": "divide",
        "inputs": (10, 0),
        "steps": "Call divide(10, 0)",
        "expected": "Program shows a friendly error message "
        "(e.g. 'Error: Cannot divide by zero') and does NOT crash",
        "check": "graceful_error",
    },
    {
        "id": "TC09",
        "scenario": "Division producing a decimal result",
        "function": "divide",
        "inputs": (7, 2),
        "steps": "Call divide(7, 2)",
        "expected": "3.5",
        "check": "value",
        "expected_value": 3.5,
    },
    {
        "id": "TC10",
        "scenario": "Power / exponent calculation",
        "function": "power",
        "inputs": (2, 3),
        "steps": "Call power(2, 3)",
        "expected": "8",
        "check": "value",
        "expected_value": 8,
    },
    {
        "id": "TC11",
        "scenario": "Square root of a positive number",
        "function": "square_root",
        "inputs": (16,),
        "steps": "Call square_root(16)",
        "expected": "4.0",
        "check": "value",
        "expected_value": 4.0,
    },
    {
        "id": "TC12",
        "scenario": "Square root of a negative number",
        "function": "square_root",
        "inputs": (-9,),
        "steps": "Call square_root(-9)",
        "expected": "Program shows a friendly error message "
        "(e.g. 'Error: Cannot compute square root of a negative number') "
        "and does NOT crash",
        "check": "graceful_error",
    },
    {
        "id": "TC13",
        "scenario": "Addition with decimal numbers",
        "function": "add",
        "inputs": (2.5, 3.1),
        "steps": "Call add(2.5, 3.1)",
        "expected": "5.6",
        "check": "value",
        "expected_value": 5.6,
    },
    {
        "id": "TC14",
        "scenario": "Multiplication with large numbers",
        "function": "multiply",
        "inputs": (123456, 789),
        "steps": "Call multiply(123456, 789)",
        "expected": "97406784",
        "check": "value",
        "expected_value": 97406784,
    },
    {
        "id": "TC15",
        "scenario": "Divide two negative numbers",
        "function": "divide",
        "inputs": (-20, -4),
        "steps": "Call divide(-20, -4)",
        "expected": "5.0",
        "check": "value",
        "expected_value": 5.0,
    },
]
